# Generated by Django 3.0.7 on 2020-07-06 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=128, unique=True, verbose_name='Country')),
            ],
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdivision', models.CharField(max_length=128, null=True, verbose_name='Province, Region or City')),
                ('alias_for_population', models.CharField(max_length=128, verbose_name='Alias')),
                ('fips', models.IntegerField(null=True, verbose_name='FIPS US inner number')),
                ('admin2', models.CharField(max_length=128, null=True, verbose_name='Admin2 County name. US only')),
                ('lat', models.DecimalField(decimal_places=16, max_digits=19, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=19, null=True, verbose_name='Longitude')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.Country')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField()),
                ('confirmed', models.PositiveIntegerField(default=0, verbose_name='Confirmed')),
                ('deaths', models.PositiveIntegerField(default=0, verbose_name='Deaths')),
                ('recovered', models.PositiveIntegerField(default=0, verbose_name='Recovered')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.Country')),
                ('subdivision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.Subdivision')),
            ],
        ),
        migrations.CreateModel(
            name='MainTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.PositiveIntegerField(verbose_name='Confirmed')),
                ('deaths', models.PositiveIntegerField(verbose_name='Deaths')),
                ('recovered', models.PositiveIntegerField(verbose_name='Recovered')),
                ('active', models.IntegerField(verbose_name='Active')),
                ('last_update', models.DateTimeField(verbose_name='Last update')),
                ('incidence_rate', models.DecimalField(blank=True, decimal_places=16, max_digits=25, null=True, verbose_name='Incidence rate')),
                ('case_fatality_ratio', models.DecimalField(decimal_places=16, default=0, max_digits=25, null=True, verbose_name='Case fatality ratio')),
                ('region_population', models.PositiveIntegerField(default=0, verbose_name='Region population')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.Country')),
                ('subdivision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.Subdivision')),
            ],
        ),
        migrations.AddConstraint(
            model_name='subdivision',
            constraint=models.UniqueConstraint(fields=('admin2', 'country', 'fips'), name='uq_subdivison'),
        ),
    ]
