# Generated by Django 3.0.1 on 2020-06-26 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fips', models.PositiveIntegerField(blank=True, verbose_name='FIPS')),
                ('admin2', models.CharField(max_length=128, verbose_name='Admin2')),
                ('province_state', models.CharField(max_length=128, verbose_name='Province')),
                ('country_region', models.CharField(max_length=128, verbose_name='Country_region')),
                ('last_update', models.CharField(max_length=128, verbose_name='last_update')),
                ('lat', models.DecimalField(decimal_places=16, default=0, max_digits=19, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=16, default=0, max_digits=19, verbose_name='Longitude')),
                ('confirmed', models.PositiveIntegerField(default=0, verbose_name='Confirmed')),
                ('deaths', models.PositiveIntegerField(default=0, verbose_name='Deaths')),
                ('recovered', models.PositiveIntegerField(default=0, verbose_name='Recovered')),
                ('active', models.PositiveIntegerField(default=0, verbose_name='Active')),
                ('incidence_rate', models.DecimalField(blank=True, decimal_places=16, max_digits=19, verbose_name='Incidence_rate')),
                ('case_fatality_ratio', models.DecimalField(decimal_places=16, default=0, max_digits=19, verbose_name='Case_fatality_ratio')),
                ('testing_rate', models.DecimalField(decimal_places=16, default=0, max_digits=19, verbose_name='Testin_rate')),
                ('hospitalization_rate', models.DecimalField(decimal_places=16, default=0, max_digits=19, verbose_name='Hospitalization_rate')),
                ('region_population', models.PositiveIntegerField(default=0, verbose_name='Region population')),
                ('region_limit', models.PositiveIntegerField(default=0, verbose_name='Region limit')),
            ],
        ),
    ]
