# Generated by Django 3.0.1 on 2020-06-29 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_region', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='Country')),
            ],
        ),
        migrations.CreateModel(
            name='MainTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.PositiveIntegerField(default=0, verbose_name='Confirmed')),
                ('deaths', models.PositiveIntegerField(default=0, verbose_name='Deaths')),
                ('recovered', models.PositiveIntegerField(default=0, verbose_name='Recovered')),
                ('active', models.PositiveIntegerField(default=0, verbose_name='Active')),
                ('incidence_rate', models.DecimalField(blank=True, decimal_places=16, max_digits=19, verbose_name='Incidence rate')),
                ('case_fatality_ratio', models.DecimalField(decimal_places=16, default=0, max_digits=19, verbose_name='Case fatality ratio')),
                ('testing_rate', models.DecimalField(decimal_places=16, default=0, max_digits=19, verbose_name='Testing rate')),
                ('hospitalization_rate', models.DecimalField(decimal_places=16, default=0, max_digits=19, verbose_name='Hospitalization_rate')),
                ('region_population', models.PositiveIntegerField(default=0, verbose_name='Region population')),
                ('region_limit', models.PositiveIntegerField(default=0, verbose_name='Region limit')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField()),
                ('confirmed', models.PositiveIntegerField(default=0, verbose_name='Confirmed')),
                ('deaths', models.PositiveIntegerField(default=0, verbose_name='Deaths')),
                ('recovered', models.PositiveIntegerField(default=0, verbose_name='Recovered')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.MainTable')),
            ],
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdivision', models.CharField(default=0, max_length=128, verbose_name='Province, Region or City')),
                ('fips', models.PositiveIntegerField(blank=True, verbose_name='FIPS US inner number')),
                ('admin2', models.CharField(max_length=128, verbose_name='Admin2 County name. US only')),
                ('last_update', models.CharField(max_length=128, verbose_name='Last update')),
                ('lat', models.DecimalField(decimal_places=16, default=0.0, max_digits=19, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=16, default=0.0, max_digits=19, verbose_name='Longitude')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Country')),
            ],
        ),
        migrations.AddField(
            model_name='maintable',
            name='subdivision',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='maintable', to='mainapp.Subdivision'),
        ),
    ]
